<a href="https://colab.research.google.com/github/ZabalaGaston/HPC/blob/main/Zabala_Gaston_ejercicio_2_CPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 Introducción

Trasponer una matriz cuadrada [1]

<center>(A^t){ij}=A{ji},1 <= m, 1 <= j <= n </center>

#2 Armado del ambiente

No son necesarios ejecuciones previas del armado del ambiente.

#3 Desarrollo

In [ ]:
#@title 3.1 Parámetros de ejecución { vertical-output: true }
#@title 3.1.1 Ingrese el orden { vertical-output: true }

ordenMatriz =   43 #@param {type:"slider", min:0, max:100, step:1}

# --------------------------------------------
from datetime import datetime
tiempo_total = datetime.now()
import numpy as np

# --------------------------------------------
# Definición de función que transforma el tiempo en  milisegundos 
tiempo_en_ms = lambda dt:(dt.days * 24 * 60 * 60 + dt.seconds) * 1000 + dt.microseconds / 1000.0

def crearMatriz(orden):
  m = np.random.randint(100, 1000, (ordenMatriz, ordenMatriz))
  return m.astype( np.float32())

def trasponerMatriz(mo,mt):
  on = len(mo) #filas
  for i in range(on):
    for j in range(on):
      mt[i][j] = mo[j][i]

# --------------------------------------------
# CPU - Defino la memoria de los vectores en cpu.

matriz = crearMatriz(ordenMatriz)
matrizTraspuesta = crearMatriz(ordenMatriz)

try:
    
  tiempo_traspuesta = datetime.now()

# CPU - Llamo a la función trasponerMatriz - Función principal

  trasponerMatriz(matriz,matrizTraspuesta)

  tiempo_traspuesta = datetime.now() - tiempo_traspuesta
  
# --------------------------------------------

  tiempo_total = datetime.now() - tiempo_total

  print("Tiempo Total: ", tiempo_en_ms( tiempo_total ), "[ms]" )
  print("Tiempo bucle: ", tiempo_en_ms( tiempo_traspuesta ), "[ms]" )

  print("Matriz original\n", matriz)
  print("\nMatriz traspuesta\n",matrizTraspuesta)

except Exception as IndexError:
  print("Error:","La matriz debe tener un orden mayor a 1")
except Exception as e: 
  print(e.args)

Tiempo Total:  1.584 [ms]
Tiempo bucle:  1.062 [ms]
Matriz original
 [[640. 927. 413. ... 806. 445. 621.]
 [189. 544. 217. ... 282. 404. 843.]
 [898. 876. 449. ... 482. 558. 548.]
 ...
 [959. 549. 578. ... 263. 662. 639.]
 [619. 922. 531. ... 835. 802. 449.]
 [872. 794. 428. ... 967. 148. 588.]]

Matriz traspuesta
 [[640. 189. 898. ... 959. 619. 872.]
 [927. 544. 876. ... 549. 922. 794.]
 [413. 217. 449. ... 578. 531. 428.]
 ...
 [806. 282. 482. ... 263. 835. 967.]
 [445. 404. 558. ... 662. 802. 148.]
 [621. 843. 548. ... 639. 449. 588.]]


#Tabla de pasos de ejecución del programa

Procesador | Función | Detalle
------------|---------|----------
CPU      |  @param                | Ingresar el orden de la matriz.
CPU      |  import                | Importar los módulos para funcionar.
CPU      |  datetime.now()        | Tomar el tiempo actual.
CPU      |  crearMatriz()         | Crear y cargar valores a la matriz original.
CPU      |  crearMatriz()         | Crear matriz traspuesta (matrizTraspuesta).
CPU      |  datetime.now()        | Tomar el tiempo actual.
CPU      |  trasponerMatriz()     | Trasponer la matriz original.
CPU      | datetime.now() - tiempo_traspuesta | Calcular tiempo total en trasponerMatriz.
CPU      |  datetime.now() - tiempo_total | Calcular el tiempo total.
CPU      |  tiempo_en_ms( time ) | Transformar tiempos en milisegundos.
CPU      |  print()               | Mostrar estadísticas.
CPU      |  print()            | Mostrar matriz original y matriz traspuesta.


---
# 6 Bibliografía

[1] Tutorial Point Colab: [PDF](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/markdown-cheatsheet-online.pdf)

[2] Matriz traspuesta: [Enlace](https://es.wikipedia.org/wiki/Matriz_transpuesta)

6 Bibliografía
[1] Tutorial Point Colab: PDF

[2] Modelo color HSV: Enlace