<a href="https://colab.research.google.com/github/ZabalaGaston/HPC/blob/main/Zabala_Gaston_ejercicio_2_CPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 Introducción

Una matriz traspuesta es el resultado de reordenar la matriz original mediantel cambio de filas por columnas y las columnas por filas en una nueva matriz. [3][2]



<center>(A^t){ij}=A{ji},1 <= m, 1 <= j <= n </center> 

En este cuaderno, dejaré plasmado el algoritmo para trasponer una matriz cuadrada.

#2 Armado del ambiente

No son necesarios ejecuciones previas del armado del ambiente.

#3 Desarrollo

Ejecución del algoritmo para trasponer una matriz.

In [3]:
#@title 3.1 Parámetros de ejecución { vertical-output: true }
#@title 3.1.1 Ingrese el orden { vertical-output: true }

ordenMatriz =   10000#@param {type:"integer"}

# --------------------------------------------
from datetime import datetime
tiempo_total = datetime.now()
import numpy as np

# --------------------------------------------
# Definición de función que transforma el tiempo en  milisegundos 
tiempo_en_ms = lambda dt:(dt.days * 24 * 60 * 60 + dt.seconds) * 1000 + dt.microseconds / 1000.0

def crearMatriz(orden):
  m = np.random.randint(100, 1000, (ordenMatriz, ordenMatriz))
  return m.astype( np.float32())

def trasponerMatriz(mo,mt):
  on = len(mo) #filas
  for i in range(on):
    for j in range(on):
      mt[i][j] = mo[j][i]

# --------------------------------------------
# CPU - Defino la memoria de los vectores en cpu.

try:
  if ordenMatriz <= 0:
    raise ValueError("Error: el orden de la matriz debe ser mayor a 0");

  matriz = crearMatriz(ordenMatriz)
  matrizTraspuesta = crearMatriz(ordenMatriz)

  tiempo_traspuesta = datetime.now()

# CPU - Llamo a la función trasponerMatriz - Función principal

  trasponerMatriz(matriz,matrizTraspuesta)

  tiempo_traspuesta = datetime.now() - tiempo_traspuesta
  
# --------------------------------------------

  tiempo_total = datetime.now() - tiempo_total

  print("Tiempo Total: ", tiempo_en_ms( tiempo_total ), "[ms]" )
  print("Tiempo bucle: ", tiempo_en_ms( tiempo_traspuesta ), "[ms]" )

  print("Matriz original\n", matriz)
  print("\nMatriz traspuesta\n",matrizTraspuesta)

except ValueError as vr:
  print(vr)
except Exception as e: 
  print(e.args)

Tiempo Total:  63024.465 [ms]
Tiempo bucle:  60612.541 [ms]
Matriz original
 [[946. 213. 980. ... 205. 590. 534.]
 [755. 770. 669. ... 593. 669. 118.]
 [355. 704. 404. ... 622. 401. 796.]
 ...
 [206. 810. 177. ... 903. 355. 419.]
 [110. 899. 240. ... 699. 684. 446.]
 [209. 505. 314. ... 464. 344. 681.]]

Matriz traspuesta
 [[946. 755. 355. ... 206. 110. 209.]
 [213. 770. 704. ... 810. 899. 505.]
 [980. 669. 404. ... 177. 240. 314.]
 ...
 [205. 593. 622. ... 903. 699. 464.]
 [590. 669. 401. ... 355. 684. 344.]
 [534. 118. 796. ... 419. 446. 681.]]


#Tabla de pasos de ejecución del programa

Procesador | Función | Detalle
------------|---------|----------
CPU      |  @param                | Ingresar el orden de la matriz.
CPU      |  import                | Importar los módulos para funcionar.
CPU      |  datetime.now()        | Tomar el tiempo actual.
CPU      |  crearMatriz()         | Crear y cargar valores a la matriz original.
CPU      |  crearMatriz()         | Crear matriz traspuesta (matrizTraspuesta).
CPU      |  datetime.now()        | Tomar el tiempo actual.
CPU      |  trasponerMatriz()     | Trasponer la matriz original.
CPU      | datetime.now() - tiempo_traspuesta | Calcular tiempo total en trasponerMatriz.
CPU      |  datetime.now() - tiempo_total | Calcular el tiempo total.
CPU      |  tiempo_en_ms( time ) | Transformar tiempos en milisegundos.
CPU      |  print()               | Mostrar estadísticas.
CPU      |  print()            | Mostrar matriz original y matriz traspuesta.


---
# 5 Conclusiones

En este cuaderno pudimos obersvar el funcionamiento un algoritmo en serie para matrices.

Realicé la ejecución 10 veces para una matriz cuadrada de 10000 x 10000, obteniendo los siguientes resultados:

Tiempo Total:  56339.996 [ms] | Tiempo bucle:  54438.133 [ms] <br>
Tiempo Total:  56528.477 [ms] | Tiempo bucle:  54499.619 [ms] <br>
Tiempo Total:  55890.466 [ms] | Tiempo bucle:  54246.096 [ms] <br>
Tiempo Total:  58155.430 [ms] | Tiempo bucle:  56445.614 [ms] <br>
Tiempo Total:  55414.698 [ms] | Tiempo bucle:  53737.859 [ms] <br>
Tiempo Total:  55255.711 [ms] | Tiempo bucle:  53608.516 [ms] <br>
Tiempo Total:  57207.924 [ms] | Tiempo bucle:  55566.520 [ms] <br>
Tiempo Total:  55759.981 [ms] | Tiempo bucle:  54104.060 [ms] <br>
Tiempo Total:  55446.184 [ms] | Tiempo bucle:  53801.693 [ms] <br>
Tiempo Total:  55882.154 [ms] | Tiempo bucle:  54219.451 [ms] <br>

Podemos notar, que los tiempos de ejecución promedio  del programa [56187.5 ms] son muchos **mayores** a los obtenidos utilizando GPU [1920.8 ms]; esto se debe a que la matriz se va recorriendo de un par a la vez.


---
# 6 Bibliografía

[1] Tutorial Point Colab: [PDF](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/markdown-cheatsheet-online.pdf)

[2] Matriz traspuesta: [Enlace](https://es.wikipedia.org/wiki/Matriz_transpuesta)

[3] Traspuesta: [Enlace](https://economipedia.com/definiciones/matriz-traspuesta.html#:~:text=Una%20matriz%20traspuesta%20es%20el,filas%20en%20una%20nueva%20matriz)