<a href="https://colab.research.google.com/github/ZabalaGaston/HPC/blob/main/Zabala_Gaston_ejercicio_2_CPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 Introducción

Una matriz traspuesta es el resultado de reordenar la matriz original mediantel cambio de filas por columnas y las columnas por filas en una nueva matriz. [3][2]



<center>(A^t){ij}=A{ji},1 <= m, 1 <= j <= n </center> 

En este cuaderno, dejaré plasmado el algoritmo para trasponer una matriz cuadrada.

#2 Armado del ambiente

No son necesarios ejecuciones previas del armado del ambiente.

#3 Desarrollo

Ejecución del algoritmo para trasponer una matriz.

In [3]:
#@title 3.1 Parámetros de ejecución { vertical-output: true }
#@title 3.1.1 Ingrese el orden { vertical-output: true }

ordenMatriz =   1 #@param {type:"slider", min:1, max:100, step:1}

# --------------------------------------------
from datetime import datetime
tiempo_total = datetime.now()
import numpy as np

# --------------------------------------------
# Definición de función que transforma el tiempo en  milisegundos 
tiempo_en_ms = lambda dt:(dt.days * 24 * 60 * 60 + dt.seconds) * 1000 + dt.microseconds / 1000.0

def crearMatriz(orden):
  m = np.random.randint(100, 1000, (ordenMatriz, ordenMatriz))
  return m.astype( np.float32())

def trasponerMatriz(mo,mt):
  on = len(mo) #filas
  for i in range(on):
    for j in range(on):
      mt[i][j] = mo[j][i]

# --------------------------------------------
# CPU - Defino la memoria de los vectores en cpu.

matriz = crearMatriz(ordenMatriz)
matrizTraspuesta = crearMatriz(ordenMatriz)

try:
    
  tiempo_traspuesta = datetime.now()

# CPU - Llamo a la función trasponerMatriz - Función principal

  trasponerMatriz(matriz,matrizTraspuesta)

  tiempo_traspuesta = datetime.now() - tiempo_traspuesta
  
# --------------------------------------------

  tiempo_total = datetime.now() - tiempo_total

  print("Tiempo Total: ", tiempo_en_ms( tiempo_total ), "[ms]" )
  print("Tiempo bucle: ", tiempo_en_ms( tiempo_traspuesta ), "[ms]" )

  print("Matriz original\n", matriz)
  print("\nMatriz traspuesta\n",matrizTraspuesta)

except IndexError:
  print("Error:","La matriz debe tener un orden mayor a 1")
except Exception as e: 
  print(e.args)

Tiempo Total:  0.707 [ms]
Tiempo bucle:  0.069 [ms]
Matriz original
 [[136. 666. 132.]
 [227. 887. 741.]
 [903. 271. 196.]]

Matriz traspuesta
 [[136. 227. 903.]
 [666. 887. 271.]
 [132. 741. 196.]]


#Tabla de pasos de ejecución del programa

Procesador | Función | Detalle
------------|---------|----------
CPU      |  @param                | Ingresar el orden de la matriz.
CPU      |  import                | Importar los módulos para funcionar.
CPU      |  datetime.now()        | Tomar el tiempo actual.
CPU      |  crearMatriz()         | Crear y cargar valores a la matriz original.
CPU      |  crearMatriz()         | Crear matriz traspuesta (matrizTraspuesta).
CPU      |  datetime.now()        | Tomar el tiempo actual.
CPU      |  trasponerMatriz()     | Trasponer la matriz original.
CPU      | datetime.now() - tiempo_traspuesta | Calcular tiempo total en trasponerMatriz.
CPU      |  datetime.now() - tiempo_total | Calcular el tiempo total.
CPU      |  tiempo_en_ms( time ) | Transformar tiempos en milisegundos.
CPU      |  print()               | Mostrar estadísticas.
CPU      |  print()            | Mostrar matriz original y matriz traspuesta.


---
# 5 Conclusiones

Realicé la ejecución 7 veces para una matriz cuadrada de 100 x 100, obteniendo los siguientes resultados:

Tiempo Total:  11.009 [ms] | Tiempo bucle:  8.326 [ms] <br>
Tiempo Total:  07.102 [ms] | Tiempo bucle:  6.422 [ms] <br>
Tiempo Total:  06.268 [ms] | Tiempo bucle:  5.544 [ms] <br>
Tiempo Total:  11.561 [ms] | Tiempo bucle:  10.414 [ms] <br>
Tiempo Total:  07.667 [ms] | Tiempo bucle:  6.723 [ms] <br>
Tiempo Total:  06.043 [ms] | Tiempo bucle:  5.383 [ms] <br>
Tiempo Total:  10.898 [ms] | Tiempo bucle:  9.766 [ms] <br>

Podemos observar, que los tiempos de ejecución promedio  del programa [8.649 ms] son muchos **mayores** a los obtenidos utilizando GPU [2,299 ms]; esto se debe a que la matriz se va recorriendo de un par a la vez.

---
# 6 Bibliografía

[1] Tutorial Point Colab: [PDF](https://github.com/wvaliente/SOA_HPC/blob/main/Documentos/markdown-cheatsheet-online.pdf)

[2] Matriz traspuesta: [Enlace](https://es.wikipedia.org/wiki/Matriz_transpuesta)

[3] Traspuesta: [Enlace](https://economipedia.com/definiciones/matriz-traspuesta.html#:~:text=Una%20matriz%20traspuesta%20es%20el,filas%20en%20una%20nueva%20matriz)